spring:
   data:
        elasticsearch:
            cluster-name: #默认为elasticsearch
            #cluster-nodes: 127.0.0.1: #配置es节点信息，逗号分隔，如果没有指定，则启动ClientNode
            properties:
                path:
                  logs: elasticsearch/log
                  data: elasticsearch/data